### ISSUE TITLE
Ce licență au datele?

### ISSUE THREAD

**Issue by ieugen** [romania/localitati#14]
Salut,

Vreau să folosesc datele într-un proiect Apache și eventual să contribui la ele pe viitor.
Pentru asta mă interesează să știu ce licență au.

Am văzut că sunt mai multe proiecte, ar fi fain ca toate să aive licență.

Eugen

**Comment by necenzurat** [comment]
Eu le dau sub [WTFPL](https://en.wikipedia.org/wiki/WTFPL), dar daca ai aversiuni la profanități, poți folosi ce îti dă statul [aici](https://data.gov.ro/dataset?q=siruta) sau [aici](https://data.gov.ro/dataset?q=localitati)
