### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by skynet** [romania/localitati#6]
Is this data still valid in 2016?

**Comment by raku** [comment]
I thik it is, I will check this weekend

**Comment by necenzurat** [comment]
Same here, i think it's still ok, i mean cities and and sub-cities don't
dissapear.

**Comment by skynet** [comment]
Did you check? Thanks

**Comment by necenzurat** [comment]
@skynet @raku has a long weekend

**Comment by raku** [comment]
Sorry, I forgot to check 😄 postal coduri_postale.sql is same, judete-orase.sql is missing some localities
